[package]
name = "printer-daemon"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
futures-core = "0.3.28"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tokio = "1.29.1"
tokio-tungstenite = "0.20.0"
tungstenite = "0.20.0"
